Models/Record.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DT102G_Moment3.Models
{
    public class Record
    {
        // Properties and dependencies
        public int RecordId { get; set; }

        [Required(ErrorMessage = "Ange ditt för och efternamn")]
        [Display(Name = "Namn")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Ange vilket år skivan släpptes")]
        [Display(Name = "Årtal")]
        public DateTime Year { get; set; }

        [Required(ErrorMessage = "Ange artist")]
        [Display(Name = "Artist")]
        public int ArtistId { get; set; }
        public Artist Artist { get; set; }
    }
}

Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DT102G_Moment3.Data;
using DT102G_Moment3.Models;

namespace DT102G_Moment3.Controllers
{
    public class ArtistController : Controller
    {
        private readonly CollectionContext _context;

        public ArtistController(CollectionContext context)
        {
            _context = context;
        }

        // GET: Artist
        [HttpGet("/Artister")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Artists.ToListAsync());
        }

        // GET: Artist/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .FirstOrDefaultAsync(m => m.ArtistId == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Artist/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Artist/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArtistId,Name")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(artist);
        }

        // GET: Artist/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }
            return View(artist);
        }

        // POST: Artist/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArtistId,Name")] Artist artist)
        {
            if (id != artist.ArtistId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(artist.ArtistId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(artist);
        }

        // GET: Artist/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .FirstOrDefaultAsync(m => m.ArtistId == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Artist/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artists.FindAsync(id);
            _context.Artists.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artists.Any(e => e.ArtistId == id);
        }
    }
}

Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DT102G_Moment3.Data;
using DT102G_Moment3.Models;

namespace DT102G_Moment3.Controllers
{
    public class RecordController : Controller
    {
        private readonly CollectionContext _context;

        public RecordController(CollectionContext context)
        {
            _context = context;
        }

        // GET: Record
        public async Task<IActionResult> Index(string searchString) // Enable filtering result
        {
            ViewBag.Search = searchString;
            var lendings = _context.Lendings.ToList(); // Get all posts in Lending table
            ViewData["Lendings"] = lendings; // Send list to view
            var collectionContext = _context.Records.Include(item => item.Artist); // Get all posts from Records and Artists

            // If a search is made get specific data
            if (!String.IsNullOrEmpty(searchString))
            {
                collectionContext = _context.Records.Where(s => s.Name.Contains(searchString)).Include(item => item.Artist);
            }
            return View(await collectionContext.ToListAsync());
        }

        // GET: Record/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @record = await _context.Records
                .Include(item => item.Artist)
                .FirstOrDefaultAsync(m => m.RecordId == id);
            if (@record == null)
            {
                return NotFound();
            }

            return View(@record);
        }

        // GET: Record/Create
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artists, "ArtistId", "Name");
            return View();
        }

        // POST: Record/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RecordId,Name,Year,ArtistId")] Record @record)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@record);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artists, "ArtistId", "ArtistId", @record.ArtistId);
            return View(@record);
        }

        // GET: Record/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @record = await _context.Records.FindAsync(id);
            if (@record == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_context.Artists, "ArtistId", "Name", @record.ArtistId);
            return View(@record);
        }

        // POST: Record/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RecordId,Name,Year,ArtistId")] Record @record)
        {
            if (id != @record.RecordId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@record);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecordExists(@record.RecordId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artists, "ArtistId", "ArtistId", @record.ArtistId);
            return View(@record);
        }

        // GET: Record/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @record = await _context.Records
                .Include(item => item.Artist)
                .FirstOrDefaultAsync(m => m.RecordId == id);
            if (@record == null)
            {
                return NotFound();
            }

            return View(@record);
        }

        // POST: Record/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @record = await _context.Records.FindAsync(id);
            _context.Records.Remove(@record);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecordExists(int id)
        {
            return _context.Records.Any(e => e.RecordId == id);
        }
    }
}

Views/Record/Create.cshtml
@model DT102G_Moment3.Models.Record

@{
    ViewData["Title"] = "Lägg till skiva";
}

<h1>Lägg till skiva</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId">
                    <option value="">Välj en artist</option>
                </select>
                <span asp-validation-for="ArtistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Record/Delete.cshtml
@model DT102G_Moment3.Models.Record

@{
    ViewData["Title"] = "Radera skiva";
}

<h1>Radera skiva</h1>

<h4>Är du säker på att du vill radera?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RecordId" />
        <input type="submit" value="Radera" class="btn btn-danger" /> |
        <a asp-action="Index">Tillbaka</a>
    </form>
</div>

Views/Record/Details.cshtml
@model DT102G_Moment3.Models.Record

@{
    ViewData["Title"] = "Detaljer om skiva";
}

<h1>Detaljer om skiva</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RecordId">Editera</a> |
    <a asp-action="Index">Tillbaka</a>
</div>

Views/Record/Edit.cshtml
@model DT102G_Moment3.Models.Record

@{
    ViewData["Title"] = "Editera skiva";
}

<h1>Editera skiva</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RecordId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId"></select>
                <span asp-validation-for="ArtistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Record/Index.cshtml
@model IEnumerable<DT102G_Moment3.Models.Record>

@{
    ViewData["Title"] = "Skivor";
}

<h1>Skivor</h1>

<!-- Search function -->
<form asp-controller="Record" asp-action="Index" method="get">
    <p>
        <input type="text" class="p-2" name="SearchString" value="@ViewBag.Search" />
        <input type="submit" class="btn btn-primary" value="Sök" />
        <button type="button" class="btn btn-secondary" onclick="location.href = '@Url.Action("Index", "Record")'">Återställ</button>
    </p>
</form>

<p>
    <a asp-action="Create">Lägg till skiva</a> |
    <a asp-controller="Artist" asp-action="Index">Lägg till artist</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist.Name)
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Artist.Name)
                </td>
                <td>
                    @{
                        // Check if id exist in Lendings table
                        List<Lending> lendings = ViewData["Lendings"] as List<Lending>;
                        if (lendings.Exists(x => x.RecordId == item.RecordId))
                        {
                            <p>Utlånad</p>
                        }
                        else
                        {
                            <p>Finns på lager</p>
                        }
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.RecordId">Editera</a> |
                    <a asp-action="Details" asp-route-id="@item.RecordId">Detaljer</a> |
                    <a asp-action="Delete" asp-route-id="@item.RecordId">Radera</a>
                </td>
            </tr>
        }
    </tbody>
</table>